codecov:
  branch: master
  bot: TimDaub

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        if_no_uploads: error

    patch:
      default:
        target: "80%"
        if_no_uploads: error

  ignore:
    - "tests/*"

comment:
  layout: "header, diff, changes, sunburst, uncovered"
  behavior: default
